### OBTENER UN LISTADO DE TODOS LOS INMUEBLES
GET http://localhost:3000/api/inmuebles

### DAR DE ALTA UN NUEVO INMUEBLE
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
  "piso": "7",
  "letra": "A",
  "extension": 140,
  "numHabitaciones": 5,
  "alquilado": false,
  "nombrePropietario": "Gonzalo Atienzar",
  "emailContacto": "Gonati@example.com"
}

### ACTUALIZAR LOS DATOS DE UN INMUEBLE
PUT http://localhost:3000/api/inmuebles/645d739ee9829b11ab5ba7a2
Content-Type: application/json

{
    "alquilado": true
    
}


### BORRAR LOS DATOS DE UN INMUEBLE
DELETE http://localhost:3000/api/inmuebles/645d77dcb40d5580a6334f5a